name: Create Tag
on:
  pull_request:
    branches:
      - "main"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --all --tags
      - name: Get Crate Version
        uses: thebongy/version-check@v1
        id: version_get
        with:
          file: Cargo.toml
          tagFormat: v${version}
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.version_get.outputs.releaseVersion }}',
              sha: context.sha
            })