name: Check Tag
on:
  pull_request:
    branches:
      - "main"

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --all --tags
      - name: Check Release Version
        uses: thebongy/version-check@v1
        id: version_get
        with:
          file: Cargo.toml
          tagFormat: v${version}
          failBuild: true